apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: template-library
  description: All Backstage templates
spec:
  type: url
  targets:
    # - ./simple-readme/template.yaml
    # - ./1st-template/template.yaml
     - ./homelab-service-template/template.yaml